FROM alpine:3.17.1
MAINTAINER Barbara Novak <bnovak@factorial.bio>

ENV SAMTOOLS_VERSION 1.18

RUN apk add --update autoconf automake make gcc musl-dev perl bash zlib-dev bzip2-dev xz-dev curl-dev openssl-dev ncurses-dev \
  &&  wget https://github.com/samtools/samtools/releases/download/${SAMTOOLS_VERSION}/samtools-${SAMTOOLS_VERSION}.tar.bz2 \
  && tar jxf samtools-${SAMTOOLS_VERSION}.tar.bz2 \
  && cd samtools-${SAMTOOLS_VERSION}/ \
  && ./configure \
  && make install \
  && apk del autoconf automake gcc curl musl-dev make \ 
  && cd .. && rm -r samtools-*

